/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import util.SUtility;

/**
 *
 * @author UPHM
 */
public class DlgAddInventory extends javax.swing.JDialog {

    /**
     * Creates new form DlgAddInventory
     */
    private Connection myConn = null;
    private PreparedStatement myStmt = null;
    private ResultSet myRs = null;
    PnlInsertInventory parent;

    public DlgAddInventory(PnlInsertInventory parent, boolean modal, Connection conn) {
        initComponents();
        setLocationRelativeTo(null);
        myConn = conn;
        this.parent = parent;
    }

//    private void insertToTable() {
//        Object data[] = {txtDlgInventoryCode.getText(),
//            txaDlgInventoryDescription.getText(),
//            Double.valueOf(txtDlgInventoryPrice.getText()),
//            Integer.valueOf(txtDlgInventoryOpening.getText()),
//            Integer.valueOf(txtDlgInventoryIn.getText()),
//            Integer.valueOf(txtDlgInventoryOut.getText()),
//            
//        };
//        DefaultTableModel tableModel = (DefaultTableModel) tblCustomer.getModel();
//        tableModel.addRow(data);
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDlgInventoryCode = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaDlgInventoryDescription = new javax.swing.JTextArea();
        btnDlgInventoryInsert = new javax.swing.JButton();
        txtDlgInventoryPrice = new javax.swing.JTextField();
        txtDlgInventoryIn = new javax.swing.JTextField();
        txtDlgInventoryOpening = new javax.swing.JTextField();
        txtDlgInventoryOut = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Code :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Description :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Price :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Opening :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("In :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Out :");

        txaDlgInventoryDescription.setColumns(20);
        txaDlgInventoryDescription.setRows(5);
        jScrollPane1.setViewportView(txaDlgInventoryDescription);

        btnDlgInventoryInsert.setText("Insert");
        btnDlgInventoryInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDlgInventoryInsertActionPerformed(evt);
            }
        });

        txtDlgInventoryOpening.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDlgInventoryOpeningActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDlgInventoryCode, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDlgInventoryPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDlgInventoryIn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDlgInventoryOpening, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDlgInventoryOut, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(btnDlgInventoryInsert)))
                .addContainerGap(212, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDlgInventoryCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDlgInventoryPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDlgInventoryOpening, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDlgInventoryIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDlgInventoryOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btnDlgInventoryInsert)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDlgInventoryOpeningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDlgInventoryOpeningActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDlgInventoryOpeningActionPerformed

    private void btnDlgInventoryInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDlgInventoryInsertActionPerformed
        if (!txtDlgInventoryPrice.getText().trim().isEmpty() && !txtDlgInventoryCode.getText().trim().isEmpty()
                && !txaDlgInventoryDescription.getText().trim().isEmpty()) {
            if (txtDlgInventoryOpening.getText().trim().isEmpty()) {
                txtDlgInventoryOpening.setText("0");
            }
            if (txtDlgInventoryIn.getText().trim().isEmpty()) {
                txtDlgInventoryIn.setText("0");
            }
            if (txtDlgInventoryOut.getText().trim().isEmpty()) {
                txtDlgInventoryOut.setText("0");
            }
            parent.insertToTable(txtDlgInventoryCode.getText(), txaDlgInventoryDescription.getText(),
                    Double.valueOf(txtDlgInventoryPrice.getText()), Integer.valueOf(txtDlgInventoryOpening.getText()),
                    Integer.valueOf(txtDlgInventoryIn.getText()), Integer.valueOf(txtDlgInventoryOut.getText()));
            txtDlgInventoryCode.setText("");
            txaDlgInventoryDescription.setText("");
            txtDlgInventoryPrice.setText("");
            txtDlgInventoryIn.setText("");
            txtDlgInventoryOut.setText("");
            txtDlgInventoryOpening.setText("");
            dispose();
        }else {
            SUtility.msg(this, "Invalid Input");
        }
    }//GEN-LAST:event_btnDlgInventoryInsertActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDlgInventoryInsert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txaDlgInventoryDescription;
    private javax.swing.JTextField txtDlgInventoryCode;
    private javax.swing.JTextField txtDlgInventoryIn;
    private javax.swing.JTextField txtDlgInventoryOpening;
    private javax.swing.JTextField txtDlgInventoryOut;
    private javax.swing.JTextField txtDlgInventoryPrice;
    // End of variables declaration//GEN-END:variables
}
