/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author UPHM
 */
public class DlgEditJurnalAddJurnalTransaction extends javax.swing.JDialog {

    /**
     * Creates new form DlgCreateJurnalAddJurnalTransaction
     */
    private Connection myConn = null;
    private PreparedStatement myStmt = null;
    private ResultSet myRs = null;
    PnlEditJurnal parent;
    private JTable table;

    public DlgEditJurnalAddJurnalTransaction(PnlEditJurnal parent, boolean modal, Connection conn,JTable table) {
        initComponents();
        setLocationRelativeTo(null);
        myConn = conn;
        generateComboBoxChartName();
        this.parent = parent;
        this.table=table;
    }

    private void executeAddTransaction() {
        DefaultTableModel tableModel = (DefaultTableModel) table.getModel();
         if(txtEditJurnalDebit.getText().isEmpty()){
                txtEditJurnalDebit.setText("0");
            }
            if(txtEditJurnalKredit.getText().isEmpty()){
                txtEditJurnalKredit.setText("0");
            }
        Object data[] = {txtEditJurnalChartNo.getText(),cboEditJurnalChartName.getSelectedItem().toString(),Double.valueOf(txtEditJurnalDebit.getText()), Double.valueOf(txtEditJurnalKredit.getText())};
        tableModel.addRow(data);
    }

    private void generateComboBoxChartName() {
        try {
            cboEditJurnalChartName.removeAllItems();
            myStmt = myConn.prepareStatement("select * from account_chart");
            // Execute SQL query
            myRs = myStmt.executeQuery();
            ArrayList<String> chartName = new ArrayList<>();
            // Process result set
            while (myRs.next()) {
                chartName.add(myRs.getString("chart_name"));
            }
            for (String a : chartName) {
                cboEditJurnalChartName.addItem(a);
            }
        } catch (SQLException ex) {
            Logger.getLogger(DlgEditJurnalAddJurnalTransaction.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void generateChartNumber() {
        try {
            ;
            myStmt = myConn.prepareStatement("select * from account_chart where chart_name=?;");
            myStmt.setString(1, cboEditJurnalChartName.getSelectedItem().toString());
            // Execute SQL query
            myRs = myStmt.executeQuery();

            // Process result set
            while (myRs.next()) {
                txtEditJurnalChartNo.setText(myRs.getString("chart_no"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(DlgEditJurnalAddJurnalTransaction.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtEditJurnalChartNo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        cboEditJurnalChartName = new javax.swing.JComboBox<>();
        txtEditJurnalDebit = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEditJurnalKredit = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtEditJurnalChartNo.setEditable(false);
        txtEditJurnalChartNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditJurnalChartNoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Chart No :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Chart Name :");

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        cboEditJurnalChartName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboEditJurnalChartNameActionPerformed(evt);
            }
        });

        txtEditJurnalDebit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditJurnalDebitActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Debit :");

        txtEditJurnalKredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditJurnalKreditActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Kredit :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtEditJurnalKredit, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtEditJurnalDebit, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAdd)
                            .addComponent(txtEditJurnalChartNo, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboEditJurnalChartName, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(199, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtEditJurnalChartNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cboEditJurnalChartName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtEditJurnalDebit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtEditJurnalKredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(btnAdd)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEditJurnalChartNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditJurnalChartNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditJurnalChartNoActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
//        parent.generateTable();
        executeAddTransaction();
        dispose();
        parent.generateTotal();
    }//GEN-LAST:event_btnAddActionPerformed

    private void cboEditJurnalChartNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboEditJurnalChartNameActionPerformed
        generateChartNumber();
    }//GEN-LAST:event_cboEditJurnalChartNameActionPerformed

    private void txtEditJurnalDebitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditJurnalDebitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditJurnalDebitActionPerformed

    private void txtEditJurnalKreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditJurnalKreditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditJurnalKreditActionPerformed

    /**
     * @param args the command line arguments
     */
//  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JComboBox<String> cboEditJurnalChartName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtEditJurnalChartNo;
    private javax.swing.JTextField txtEditJurnalDebit;
    private javax.swing.JTextField txtEditJurnalKredit;
    // End of variables declaration//GEN-END:variables
}
