package main;

import injection.Inject;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER
 */
public class PnlGeneralLedger extends javax.swing.JPanel {

    /**
     * Creates new form PnlGeneralLedger
     */
    private Connection myConn = null;
    private PreparedStatement myStmt = null;
    private ResultSet myRs = null;
    
    Inject inject;
    
    public PnlGeneralLedger(Connection conn,Inject inject) {
        initComponents();
        myConn=conn;
        this.inject=inject;  
    }
    
    public void generateData(){
        txtGeneralLedgerChartName.setText(inject.getGeneralLedgerMonth().getChartName());
        txtGeneralLedgerChartNo.setText(String.valueOf(inject.getGeneralLedgerMonth().getAccChartNumber()));
        txtGeneralLedgerPeriod.setText(inject.getGeneralLedgerMonth().getYear()+"-"+ inject.getGeneralLedgerMonth().getMonth());
    }
    
    public void generateTotal(){
        double tDebit=0;
        double tKredit=0;
        for(int row=0;row<tblGeneralLedger.getRowCount();row++){
            tDebit+=Double.valueOf(tblGeneralLedger.getValueAt(row,3).toString());
            tKredit+=Double.valueOf(tblGeneralLedger.getValueAt(row,4).toString());
        }
        txtGeneralLedgerTotalDebit.setText(String.valueOf(tDebit));
        txtGeneralLedgerTotalKredit.setText(String.valueOf(tKredit));
    }
    
    public void generateTable(String chartNo,int month,int year){
         try {
            DefaultTableModel tableModel = (DefaultTableModel) tblGeneralLedger.getModel();
            for (int i = tblGeneralLedger.getRowCount() - 1; i >= 0; i--) {
                tableModel.removeRow(i);
            }

            myStmt = myConn.prepareStatement("select * from jurnal_fulldata where chart_no=? &&"
                    + " extract(month from date)=? && extract(year from date)=?;");
            // Execute SQL query
            myStmt.setString(1,chartNo);
            myStmt.setInt(2,month);
            myStmt.setInt(3,year);
            myRs = myStmt.executeQuery();
            
            double balance=0;
            // Process result set
            if (myRs.isBeforeFirst()) {
                while (myRs.next()) {
                    balance+=myRs.getDouble("debit");
                    balance-=myRs.getDouble("kredit");
                    Object data[] = {myRs.getString("date"), myRs.getString("jurnal_no"),myRs.getString("description"), myRs.getDouble("debit"), myRs.getDouble("kredit"),balance};
                    tableModel.addRow(data);
                }
            }
            
 
        } catch (SQLException ex) {
            Logger.getLogger(DlgLogin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NullPointerException ex) {

        }
    }

    public void toPDF() {
        try {
            DefaultTableModel table= (DefaultTableModel) tblGeneralLedger.getModel();
            JRTableModelDataSource datasource= new JRTableModelDataSource(table);
            String path="";
            JasperPrint jasperPrint = null;
            JasperReport jasperReport = JasperCompileManager.compileReport(path);
            Map parameters = new HashMap();
//            parameters.put("id_transaksi", id_transaksi);
            jasperPrint = JasperFillManager.fillReport(jasperReport, parameters, myConn);
            JasperViewer.viewReport(jasperPrint, false);
        } catch (JRException ex) {
            Logger.getLogger(PnlGeneralLedger.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtGeneralLedgerChartNo = new javax.swing.JTextField();
        txtGeneralLedgerChartName = new javax.swing.JTextField();
        txtGeneralLedgerPeriod = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGeneralLedger = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtGeneralLedgerTotalDebit = new javax.swing.JTextField();
        txtGeneralLedgerTotalKredit = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        toPdf = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Chart No :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Chart Name :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Period :");

        txtGeneralLedgerChartNo.setEditable(false);

        txtGeneralLedgerChartName.setEditable(false);
        txtGeneralLedgerChartName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGeneralLedgerChartNameActionPerformed(evt);
            }
        });

        txtGeneralLedgerPeriod.setEditable(false);

        tblGeneralLedger.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Jurnal No", "Description", "Debit", "Kredit", "Balance"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblGeneralLedger);
        if (tblGeneralLedger.getColumnModel().getColumnCount() > 0) {
            tblGeneralLedger.getColumnModel().getColumn(0).setResizable(false);
            tblGeneralLedger.getColumnModel().getColumn(1).setResizable(false);
            tblGeneralLedger.getColumnModel().getColumn(2).setResizable(false);
            tblGeneralLedger.getColumnModel().getColumn(3).setResizable(false);
            tblGeneralLedger.getColumnModel().getColumn(5).setResizable(false);
        }

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Total Debit :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Total Kredit :");

        txtGeneralLedgerTotalDebit.setEditable(false);

        txtGeneralLedgerTotalKredit.setEditable(false);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        toPdf.setText("jButton2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtGeneralLedgerTotalKredit, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtGeneralLedgerTotalDebit, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(155, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(159, 159, 159)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtGeneralLedgerPeriod)
                    .addComponent(txtGeneralLedgerChartName)
                    .addComponent(txtGeneralLedgerChartNo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(toPdf)
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtGeneralLedgerChartNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtGeneralLedgerChartName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtGeneralLedgerPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(toPdf)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtGeneralLedgerTotalDebit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtGeneralLedgerTotalKredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(94, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtGeneralLedgerChartNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGeneralLedgerChartNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGeneralLedgerChartNameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        inject.getMain().changeLayout(inject.getGeneralLedgerMonth());
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblGeneralLedger;
    private javax.swing.JButton toPdf;
    private javax.swing.JTextField txtGeneralLedgerChartName;
    private javax.swing.JTextField txtGeneralLedgerChartNo;
    private javax.swing.JTextField txtGeneralLedgerPeriod;
    private javax.swing.JTextField txtGeneralLedgerTotalDebit;
    private javax.swing.JTextField txtGeneralLedgerTotalKredit;
    // End of variables declaration//GEN-END:variables
}
