package main;

import injection.Inject;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER
 */
public class PnlViewJurnal extends javax.swing.JPanel {

    /**
     * Creates new form PnlViewJurnal
     */
    private Connection myConn = null;
    private PreparedStatement myStmt = null;
    private ResultSet myRs = null;

    Inject inject;
    
    public PnlViewJurnal(Connection conn,Inject inject) {
        initComponents();
        myConn=conn;
        this.inject=inject;

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnViewJurnalDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblViewJurnal = new javax.swing.JTable();

        btnViewJurnalDelete.setText("Delete");
        btnViewJurnalDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewJurnalDeleteActionPerformed(evt);
            }
        });

        tblViewJurnal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Jurnal No", "Date", "Chart No", "Chart Name", "Description", "Total Debit", "Total Kredit"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblViewJurnal);
        if (tblViewJurnal.getColumnModel().getColumnCount() > 0) {
            tblViewJurnal.getColumnModel().getColumn(0).setResizable(false);
            tblViewJurnal.getColumnModel().getColumn(1).setResizable(false);
            tblViewJurnal.getColumnModel().getColumn(2).setResizable(false);
            tblViewJurnal.getColumnModel().getColumn(3).setResizable(false);
            tblViewJurnal.getColumnModel().getColumn(4).setResizable(false);
            tblViewJurnal.getColumnModel().getColumn(5).setResizable(false);
            tblViewJurnal.getColumnModel().getColumn(6).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(btnViewJurnalDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(btnViewJurnalDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewJurnalDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewJurnalDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewJurnalDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnViewJurnalDelete;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblViewJurnal;
    // End of variables declaration//GEN-END:variables
}
